### PR TITLE
[VCDA-2287] Create native 1.20 K8s template version

### PR DESCRIPTION
**Pull request by ltimothy7**
Tested successfully creating k8s 1.20 template for template.yaml and template_v2.yaml

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/29)* status: 2 of 18 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXhtIOV7nRBUaFrvxn0:-MXhtIOW6fMsnLd3tlth:b-os0x2a) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/1b36bf0a2b054833503cffe8541fbc04af80ef0d/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L39)):*
> ```Shell
> systemctl restart docker
> while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done
> ```

Since the revisions for the scripts in scripts/ and scripts_v2/ are the same, we should make sure that the scripts which are common between them are exactly the same.

Download of versioned weave.yaml should also be added here. Also note that mstr.sh for this script in script/ directory should stop downloading weave.yaml and should just refer to the versioned weave.yaml file.
___
*[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/mstr.sh, line 10 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXhsttu-qa7_jKkkH9Y:-MXhsttu-qa7_jKkkH9Z:b-1qt98n) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/1b36bf0a2b054833503cffe8541fbc04af80ef0d/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/mstr.sh#L10)):*
> ```Shell
> 
> export kubever=$(kubectl version --client | base64 | tr -d '\n')
> wget --no-verbose -O /root/weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.6.5"
> ```

I think we should start following the same

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 18 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/29)* status: all files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 59 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmTVRc0Vfas0VgCWJW:-MXmTVRc0Vfas0VgCWJX:b-jast9n) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L59)):*
> ```Shell
> apt-get -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
> 
> 	# Download weave.yml to /root/weave.yml
> ```

I think the spacing at the beginning is not necessary
___
*[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cluster-upgrade/master-cni-apply.sh, line 7 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmU33G3LXSOFYCJdE9:-MXmU33G3LXSOFYCJdEA:b-rxqr4d) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cluster-upgrade/master-cni-apply.sh#L7)):*
> ```Shell
> export kubever=$(kubectl version --client | base64 | tr -d '\n')
> wget --no-verbose -O /root/weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.6.5"
> kubectl apply -f /root/weave.yml
> ```

weave needs to be versioned here as well
___
*[scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 59 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmUU1k96nNgQb4Vi4a:-MXmUU1k96nNgQb4Vi4b:b-93vftr) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L59)):*
> ```Shell
> apt-get -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
> 
> # Download weave.yml to /root/weave.yml
> ```

Oh, I think I made a mistake while I made changes to other templates. The comment here is wrong as file is downloaded to weave_v2-6-5.yml.
Can you please change the comments for the other templates as well? Or I can take it up as a separate task

**Comment by ltimothy7** [comment]
> > Reviewed 14 of 18 files at r1, 2 of 2 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/29)_ status: all files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)
> 
> _[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 59 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmTVRc0Vfas0VgCWJW:-MXmTVRc0Vfas0VgCWJX:b-jast9n) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L59)):_
> 
> > ```shell
> > apt-get -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
> > 
> > 	# Download weave.yml to /root/weave.yml
> > ```
> 
> I think the spacing at the beginning is not necessary
Thank you for catching this, I just removed it.
> 
> _[scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cluster-upgrade/master-cni-apply.sh, line 7 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmU33G3LXSOFYCJdE9:-MXmU33G3LXSOFYCJdEA:b-rxqr4d) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cluster-upgrade/master-cni-apply.sh#L7)):_
> 
> > ```shell
> > export kubever=$(kubectl version --client | base64 | tr -d '\n')
> > wget --no-verbose -O /root/weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.6.5"
> > kubectl apply -f /root/weave.yml
> > ```
> 
> weave needs to be versioned here as well
Thank you, I have versioned it.
> 
> _[scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 59 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmUU1k96nNgQb4Vi4a:-MXmUU1k96nNgQb4Vi4b:b-93vftr) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L59)):_
> 
> > ```shell
> > apt-get -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
> > 
> > # Download weave.yml to /root/weave.yml
> > ```
> 
> Oh, I think I made a mistake while I made changes to other templates. The comment here is wrong as file is downloaded to weave_v2-6-5.yml.
> Can you please change the comments for the other templates as well? Or I can take it up as a separate task

Thank you, Aniruddha, I have updated the other v2 templates

**Review by sakthisunda — APPROVED** [review]
> Reviewed 5 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/29)* status: 20 of 23 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-:-MXnkKbG-LG4PCe5mLmW:bg7igkv)* status: 20 of 23 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 3 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/29)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh, line 59 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/29#-MXmUU1k96nNgQb4Vi4a:-MXnkX-R96Z5vePR7tRV:b-y4s0bp) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/be15c7d6d81341c89b45194b53486110334b6653/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev1/cust.sh#L59)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Thank you, Aniruddha, I have updated the other v2 templates
</blockquote></details>

Thanks Tim!

**Pull request merged**
