### PR TITLE
[VCDA-5294] Native-Cluster-Creation-Fix-Due-To-Old-Containerd

### PR DESCRIPTION
**Pull request by sakthisunda**
- This fixes failing Native cluster creation that used Ubuntu-20 k8s 1.23  with old containerd 1.14 that reached end of life 
- Updated the containerd.io for template customization
- Ref: https://github.com/containerd/containerd/blob/main/RELEASES.md
- Tested cluster creation  

`Could not initialize cluster: Initialize cluster script execution failed on node ['mstr-4mb3']:['error execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR CRI]: container runtime is not running: output: time="2023-02-21T11:47:55Z" level=fatal msg="validate service connection: ubuntu-20.04_k8-1.23_weave-2.8.1 \\"unix:///run/containerd/containerd.sock
": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"\n, error: exit status 1\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher\n']`

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/68)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/68)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[`template_v2.yaml` line 9 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/68#-NPcjg2s45AUXPGEtQMV:-NPcj9If1ZZKwjitdZLr:bf2laet) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/9891f8cced45ec6a7d3b6db14aa98191848bacf7/template_v2.yaml#L9)):*
> ```YAML
>     mem: 2048
>     name: ubuntu-20.04_k8-1.23_weave-2.8.1
>     revision: 1
> ```

Please bump the revision to 2.

This will also mean we actually fill out the upgrade scripts and in the docker upgrade script we upgrade containerd alongside docker.

I will suggest we discuss this with Aashima first though. Given support for native templates has ended.

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/68)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/68)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[`template_v2.yaml` line 9 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/68#-NPcjg2s45AUXPGEtQMV:-NSCsCxX8cK9dgV4NIHs:b3tk6in) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/9891f8cced45ec6a7d3b6db14aa98191848bacf7/template_v2.yaml#L9)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please bump the revision to 2.

This will also mean we actually fill out the upgrade scripts and in the docker upgrade script we upgrade containerd alongside docker.

I will suggest we discuss this with Aashima first though. Given support for native templates has ended.

</blockquote></details>

Based on the most recent discussion, we concluded to go with just update containerd version in the template customization and do necessary documentation on template announcements

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/68#-:-NSIaS_I5KeLVMA9SAdf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
