### PR TITLE
Remove dependency on cloud.weave.works for K8s 1.21 and 1.23 v2 templates

### PR DESCRIPTION
**Pull request by rocknes**
Unfortunately cloud.weave.works has been shut down since September 30th, 2022.
We rely on this site to download weave,yaml, that defines the weave pods, that are deployed on a cluster deployed by CSE.

To remove the dependency on weave cloud, we have downloaded a copy of weave daemon set from https://github.com/weaveworks/weave/releases, configured it to pull weave 2.8.1 from gchr.io, and embedded the yaml file in template's cust.sh to make sure that the versioned weave yaml file is generated locally instead of being downloaded from cloud.weave.works.

Please note that this change will not warrant a revision bump to the template, since the software stack hasn't been changed.

Testing done:
Created K8s 1.23 templates, deployed a cluster using the template and verified that weave pods are running in the cluster and are of version 2.8.1 

Signed-off-by: Aritra Sen <sena@sena-a01.vmware.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/65)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
The ubuntu 20.04 k8s 1.23 template has no valid upgrade path :slightly_smiling_face:
I haven't tested the 1.21 upgrade, for that I will need a 1.20 cluster :neutral_face: But to be honest, both 1.20 and 1.21 templates use 2.8.1 weave, so the cni upgrade part should not get executed

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/65#-:-NEC_v0gC2uY_7Iz9iCb:bmzsvko)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @andrew-ni and @sahithi)

**Review by rocknes — COMMENTED** [review]
Yes, we could host the file on github template repo and let the script download it instead. But trying to avoid extra downloads (or points of failures - github rate limiting, wget/curl failures etc)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/65#-:-NECaGR93prWyN6Y_1Zh:b4rwk8n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-ni)

**Review by andrew-ni — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/65#-:-NECberg0JBRGXJXjMno:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Comment by kutukcub** [comment]
Tested in Lab environment with ubuntu-20.04_k8s_1.23. VM customization is working again.

**Comment by kutukcub** [comment]
> ubuntu 16.04 1.20 is not working. I checked the cust.sh and control plane and saw that cloud.weave line is there.

Any update ?

**Comment by kutukcub** [comment]
Hello,
@rocknes @arunmk @sahithi 

ubuntu 16.04 1.20, 1.19 and 1.18 templates are not working. How can we work these templates ? I tried to edit the cust.sh like 20.04 and 1.21 but it gives me an error like " touch -help"

**Pull request merged**
