### PR TITLE
[VCDA-2472] Update template yaml with version and scripts directory keys

### PR DESCRIPTION
**Pull request by Anirudh9794**
Add the following keys to template.yaml and template_v2.yaml

* version : represents the template cookbook format version
* scripts_directory: the relative path of the directory containing the scripts to install kubernetes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/35)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/35)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[template.yaml, line 4 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/35#-MbDaKwm2Ba2CAC8hmFb:-MbDaKwo-fGL7gYUFECk:b-8ktc8g) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/fea73074993a450c8c7862c461c8a2555aef67a9/template.yaml#L4)):*
> ```YAML
> # CSE versions <= 3.0 can continue to use this template cookbook.
> # CSE versions >= 3.1 must begin to use new /templateV2.yaml
> version: '1.0'
> ```

1.0.0
___
*[template_v2.yaml, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/35#-MbDaMERCM432LC8Wb0O:-MbDaMES-03Er2NL2ckF:b-8k9jn3) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/fea73074993a450c8c7862c461c8a2555aef67a9/template_v2.yaml#L1)):*
> ```YAML
> version: '2.0'
> ```

2.0.0

**Review by rocknes — COMMENTED** [review]
Also please remove compute_policy field from all templates in templatev2.yaml

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/35#-:-MbDhiQh3_vJZ71VKk8m:b-7icf5e)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/35)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[template.yaml, line 4 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/35#-MbDaKwm2Ba2CAC8hmFb:-MbDjFtTA6TOSHEC2TaO:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/fea73074993a450c8c7862c461c8a2555aef67a9/template.yaml#L4)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

1.0.0
</blockquote></details>

Done.
___
*[template_v2.yaml, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/35#-MbDaMERCM432LC8Wb0O:-MbDjGMfB5haVCiHnhog:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/fea73074993a450c8c7862c461c8a2555aef67a9/template_v2.yaml#L1)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

2.0.0
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/35#-:-MbHhCdC0nNq4x3rAyjI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
