### PR TITLE
[VCDA-1833] Push latest templates config to the master

### PR DESCRIPTION
**Pull request by sakthisunda**
- Verfied templates working as fresh template install and in cluster upgrades 
- Testing completed using CRUD on clusters:  remote_template_cookbook_url: https://raw.githubusercontent.com/vmware/container-service-extension-templates/upgrades/template.yaml
- 10.0.x, 10.1.x, 10.2.x

@rocknes @Anirudh9794 @andrew-ni

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/16)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/16)* status: 1 of 64 files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev3/cust.sh, line 1 at r3](https://reviewable.io/reviews/vmware/container-service-extension-templates/16#-MJ9KEjd1sVEi0l4IoWC:-MJ9KEjd1sVEi0l4IoWD:bhjni9c) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/c9e27370dddb520cd162f8ffaa4e831714b8a7b1/scripts/photon-v2_k8-1.12_weave-2.3.0_rev3/cust.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

This particular template was never released, so we shouldn't add scripts under this folder to master.
___
*[scripts/ubuntu-16.04_k8-1.18_weave-2.6.4_rev1/cust.sh, line 1 at r3](https://reviewable.io/reviews/vmware/container-service-extension-templates/16#-MJ9JsD8BuGf7uZkweD0:-MJ9JsD98dTav1wsD_pt:bq0voc9) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/c9e27370dddb520cd162f8ffaa4e831714b8a7b1/scripts/ubuntu-16.04_k8-1.18_weave-2.6.4_rev1/cust.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

This template doesn't exist. We should not be adding scripts under this folder. Please remove this folder from upgrades branch too.

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/16)* status: 2 of 64 files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/16)* status: 2 of 64 files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev3/cust.sh, line 1 at r3](https://reviewable.io/reviews/vmware/container-service-extension-templates/16#-MJ9KEjd1sVEi0l4IoWC:-MJ9h79B-SY1upRweL8n:b-npjukt) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/c9e27370dddb520cd162f8ffaa4e831714b8a7b1/scripts/photon-v2_k8-1.12_weave-2.3.0_rev3/cust.sh#L1)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This particular template was never released, so we shouldn't add scripts under this folder to master.
</blockquote></details>

New PR to update upgrades branch: https://reviewable.io/reviews/vmware/container-service-extension-templates/17
___
*[scripts/ubuntu-16.04_k8-1.18_weave-2.6.4_rev1/cust.sh, line 1 at r3](https://reviewable.io/reviews/vmware/container-service-extension-templates/16#-MJ9JsD8BuGf7uZkweD0:-MJ9hCyJ33k_UfkYpLWh:b-npjukt) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/c9e27370dddb520cd162f8ffaa4e831714b8a7b1/scripts/ubuntu-16.04_k8-1.18_weave-2.6.4_rev1/cust.sh#L1)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This template doesn't exist. We should not be adding scripts under this folder. Please remove this folder from upgrades branch too.
</blockquote></details>

New PR to update upgrades branch: https://reviewable.io/reviews/vmware/container-service-extension-templates/17

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/16#-:-MJBHIgUC-BUD-7Lm74l:bnfp4nl)* status: 2 of 64 files reviewed, all discussions resolved

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/16#-:-MJDAzAfDeDCP8xbGbuH:bg7igkv)* status: 1 of 46 files reviewed, all discussions resolved

**Pull request merged**
