### PR TITLE
Add v2 template definition and scripts.

### PR DESCRIPTION
**Pull request by rocknes**
Bring v2.0.0 style template declaration and scripts folder from 'upgrades' branch to 'master' branch.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 4 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45)* status: 4 of 60 files reviewed, all discussions resolved (waiting on @rocknes)

**Review by sakthisunda — APPROVED** [review]
> Reviewed 14 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45)* status: 18 of 60 files reviewed, 1 unresolved discussion (waiting on @rocknes)

*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension-templates/45#-MdbyLKt2b-YekxYAwbL:-MdbyLKt2b-YekxYAwbM:bpvq68c) (no related file):*
Under scripts_v2, we have ubuntu-16.-4_k8-1.16_weave-2.6.0_rev3 and k8-1.17 files which are not in use anymore.

---

**Review by sakthisunda — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45#-:-MdbzkG9ENTHnaLPdpjc:bnfp4nl)* status: 18 of 60 files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Review by rocknes — COMMENTED** [review]
> Reviewed 4 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45)* status: 18 of 60 files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension-templates/45#-MdbyLKt2b-YekxYAwbL:-Mdc1Ty37ABdCEMCh_Hl:bisufxi) (no related file):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Under scripts_v2, we have ubuntu-16.-4_k8-1.16_weave-2.6.0_rev3 and k8-1.17 files which are not in use anymore.
</blockquote></details>

True, I will remove them.

---

**Review by sakthisunda — APPROVED** [review]
> Reviewed 28 of 60 files at r1, 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by arunmk — APPROVED** [review]
> Reviewed 9 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Comment by arunmk** [comment]
:lgtm:

**Pull request merged**
