### PR TITLE
Fix to change repository from bintray to packages.vmware.com

### PR DESCRIPTION
**Pull request by Anirudh9794**
Change photon public repository from bintray to packages.vmware.com

Testing done:
Created a photon template successfully

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/19)

### CODE REVIEW

**Comment by ChintanShahVMware** [comment]
___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh, line 25 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/19#-MLtrLde0C0pSoTGtZgU:-MLtrLde0C0pSoTGtZgV:b-xvhplq) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/cda14dfc9ccf4ca98d515b6378dcb96be59f17c3/scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh#L25)):*
> ```Shell
> 
> # update public repository to point to packages.vmware.com
> pushd /etc/yum.repos.d
> ```

Question
Do you need to create /etc/yum.repos.d directiory or is it safe to assume that this directory exists on photon OS?

**Review by sakthisunda — APPROVED** [review]
:lgtm: (after review comments)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/19#-:-MLuAqb49G4Z8AUUc9j7:b-h3igdy)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/19)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev2/cust.sh, line 26 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/19#-MLuBeBTCT5S78rrBYAH:-MLuBeBTCT5S78rrBYAI:bpcapyt) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/cda14dfc9ccf4ca98d515b6378dcb96be59f17c3/scripts/photon-v2_k8-1.12_weave-2.3.0_rev2/cust.sh#L26)):*
> ```Shell
> # update public repository to point to packages.vmware.com
> pushd /etc/yum.repos.d
> sed -i 's/dl.bintray.com\/vmware/packages.vmware.com\/photon\/$releasever/g' photon.repo photon-updates.repo photon-extras.repo photon-debuginfo.repo
> ```

shoud dot character in dl.bintray.com also be escaped as dl\.bintray\.com?

**Comment by Anirudh9794** [comment]
___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh, line 25 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/19#-MLtrLde0C0pSoTGtZgU:-MLuHXbC5z2El7P85Duz:b-tyxlnb) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/cda14dfc9ccf4ca98d515b6378dcb96be59f17c3/scripts/photon-v2_k8-1.12_weave-2.3.0_rev1/cust.sh#L25)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Question
Do you need to create /etc/yum.repos.d directiory or is it safe to assume that this directory exists on photon OS?
</blockquote></details>

This is similar to `/etc/apt` folder in ubuntu. This directory will already be present.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/19)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ChintanShahVMware and @sakthisunda)

___
*[scripts/photon-v2_k8-1.12_weave-2.3.0_rev2/cust.sh, line 26 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/19#-MLuBeBTCT5S78rrBYAH:-MLuHwrE48JoR3yiqcXZ:b-elrnwr) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/cda14dfc9ccf4ca98d515b6378dcb96be59f17c3/scripts/photon-v2_k8-1.12_weave-2.3.0_rev2/cust.sh#L26)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

shoud dot character in dl.bintray.com also be escaped as dl\.bintray\.com? 
</blockquote></details>

I think the escaping is necessary for `/` because it will be interpreted by `sed` command. I don't think it is necessary to escape `.`

**Review by rocknes — APPROVED** [review]
I am assuming that we don't have to change the location of the photon ova in templates.yaml? 
It is also hosted on bintray, will that be changed to packages.vmware.com?
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/19#-:-MLuKWrX2gfM0ObD6s_s:b-wkc6ri)* status: all files reviewed, 2 unresolved discussions (waiting on @ChintanShahVMware and @sakthisunda)

**Comment by Anirudh9794** [comment]
I am not sure if the OVA location will change in the future but for now, the OVA hosted in bintray has no problems.

**Pull request merged**
