### PR TITLE
added v1 1.20 template to main branch

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/31)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/31#-:-MZPgTgg2a-nuGHk7GjU:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/31)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[template.yaml, line 65 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/31#-MZPz9gz5mJckFJu1oE6:-MZPz9h-BpO192S-xoXj:bmsoo6r) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00ca8f4fdcc02df8c862746abe69b96a4ff52b40/template.yaml#L65)):*
> ```YAML
>     cpu: 2
>     deprecated: false
>     description: "Ubuntu 16.04, Docker-ce 19.03.5, Kubernetes 1.17.9, weave 2.6.0"
> ```

Mark the 1.17 template as deprecated.
___
*[template.yaml, line 83 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/31#-MZPz7jY6eqoCS9t3alQ:-MZPz7jZ1_3d5ARq7AgJ:b-5rnpxq) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00ca8f4fdcc02df8c862746abe69b96a4ff52b40/template.yaml#L83)):*
> ```YAML
>       - "ubuntu-16.04_k8-1.17_weave-2.6.0"
>   - 
>     compute_policy: ""
> ```

Remove the 1.16 template

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/31)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[template.yaml, line 65 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/31#-MZPz9gz5mJckFJu1oE6:-MZQT-y787mTWS-6dgqq:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00ca8f4fdcc02df8c862746abe69b96a4ff52b40/template.yaml#L65)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Mark the 1.17 template as deprecated.
</blockquote></details>

Done.
___
*[template.yaml, line 83 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/31#-MZPz7jY6eqoCS9t3alQ:-MZQT0IpE6fOzyrY2pLT:bc9wwzt) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00ca8f4fdcc02df8c862746abe69b96a4ff52b40/template.yaml#L83)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Remove the 1.16 template
</blockquote></details>

Done. Thanks Aritra

**Pull request merged**
