### PR TITLE
[VCDA-2190] & [VCDA-2191] TemplateV2 changes and move weave to cust.sh

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

* Create templateV2.yaml which has additional template descriptor keys - `min_cse_version` and `max_cse_version`.
* Copy all the supported scripts to `scriptsV2/`
* Download weave.yaml in cust.sh instead of mstr.sh.
* Remove mstr.sh, node.sh and nfsd.sh (cluster-management scripts) from all the templates in `scriptsV2/`

Testing done:
* Create template
* Create cluster from template
* Resize cluster
* Upgrade cluster

@arunmk @rocknes @sahithi @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/24)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
There is no code in this PR that actually consumes min_cse_version etc, correct?

> Reviewed 2 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-:-MVIcA2A9WNWqxqSgnxX:bazo1cf)* status: 2 of 32 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[templateV2.yaml, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVIbQsH1boSVTCL3eI4:-MVIbQsI1OP5_bB3lPHe:b-yd5yx8) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00aaf4f4bd96a6df007f40c317591c4556cfa42e/templateV2.yaml#L1)):*
> ```YAML
> templates:
> ```

Should we call this as `templates_v2`? This is more of a loud thought. In the future, if someone uses templates.yaml unknowingly, there will be no error issued unless we make min_cse_version and max_cse_version as mandatory fields.

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/24)* status: 2 of 37 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cust.sh, line 55 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVSe4SS69Edv_oqPSZj:-MVSe4ST9FIgV6FL9Pjz:b-nsffgm) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cust.sh#L55)):*
> ```Shell
> # Download weave.yml to /root/weave.yml
> export kubever=$(kubectl version --client | base64 | tr -d '\n')
> wget --no-verbose -O /root/weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.5.2"
> ```

Better to version the downloaded file (/root/weave_<version>.yaml), else we may have some confusion during upgrade.
___
*[scriptsV2/ubuntu-16.04_k8-1.17_weave-2.6.0_rev2/cluster-upgrade/master-cni-apply.sh, line 6 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVSe_Z1AncWBodrAVqB:-MVSe_Z1AncWBodrAVqC:b-szz34q) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/ubuntu-16.04_k8-1.17_weave-2.6.0_rev2/cluster-upgrade/master-cni-apply.sh#L6)):*
> ```Shell
> 
> export kubever=$(kubectl version --client | base64 | tr -d '\n')
> wget --no-verbose -O /root/weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.6.0"
> ```

Better to version here as well like above

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 27 of 32 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/24)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[template.yaml, line 2 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVTkY6E8qz7VUbwIcN5:-MVTkY6E8qz7VUbwIcN6:bsjeewc) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/template.yaml#L2)):*
> ```YAML
> # NOTE: This template cookbook is deprecated.
> # Only CSE 3.0 and older CSE builds should use this template cookbook.
> ```

CSE versions <= 3.0 can continue to use this template cookbook.
CSE versions >= 3.1 must begin to use new /templateV2.yaml
___
*[templateV2.yaml, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVIbQsH1boSVTCL3eI4:-MVTl9EMBRr4C490wNTC:b-h0owuk) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00aaf4f4bd96a6df007f40c317591c4556cfa42e/templateV2.yaml#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Should we call this as `templates_v2`? This is more of a loud thought. In the future, if someone uses templates.yaml unknowingly, there will be no error issued unless we make min_cse_version and max_cse_version as mandatory fields. 
</blockquote></details>

min and max are indeed mandatory fields starting CSE 3.1
___
*[scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cust.sh, line 55 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVSe4SS69Edv_oqPSZj:-MVTlrc83wd7OBGmUXlW:b32v57) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cust.sh#L55)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Better to version the downloaded file (/root/weave_<version>.yaml), else we may have some confusion during upgrade.
</blockquote></details>

+1
___
*[scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cluster-upgrade/master-cni-apply.sh, line 6 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVTmUoaCtdB1du9nPhi:-MVTmUoaCtdB1du9nPhj:bxqi2f0) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cluster-upgrade/master-cni-apply.sh#L6)):*
> ```Shell
> 
> export kubever=$(kubectl version --client | base64 | tr -d '\n')
> wget --no-verbose -O /root/weave.yml "https://cloud.weave.works/k8s/net?k8s-version=$kubever&v=2.5.2"
> ```

We can remove "wget" from here and other cni-apply files?

**Review by Anirudh9794 — COMMENTED** [review]
@arunmk The code to consume min_cse_version will be in CSE code base. I will make these changes in CSE as part of a different task

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-:-MVXCBua53fI3mOHKxaS:b5u7rac)* status: 26 of 37 files reviewed, 5 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[template.yaml, line 2 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVTkY6E8qz7VUbwIcN5:-MVTzNt_0c6zPGHlL6fZ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/template.yaml#L2)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

CSE versions <= 3.0 can continue to use this template cookbook.
CSE versions >= 3.1 must begin to use new /templateV2.yaml
</blockquote></details>

Done.
___
*[scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cust.sh, line 55 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVSe4SS69Edv_oqPSZj:-MVU0CP2BU5oyryNVEIS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cust.sh#L55)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cluster-upgrade/master-cni-apply.sh, line 6 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVTmUoaCtdB1du9nPhi:-MVU0JYN74syrCQaTVin:bbnogrg) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/photon-v2_k8-1.14_weave-2.5.2_rev3/cluster-upgrade/master-cni-apply.sh#L6)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can remove "wget" from here and other cni-apply files?
</blockquote></details>

I think this is still needed here. Cust.sh of the target template won't run if user is trying to upgrade the cluster. I changed file name to include version.
___
*[scriptsV2/ubuntu-16.04_k8-1.17_weave-2.6.0_rev2/cluster-upgrade/master-cni-apply.sh, line 6 at r2](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVSe_Z1AncWBodrAVqB:-MVU0d5D066wbn76L7rF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/61071b27e1b3788d5dca0146a282fa88c40e0c1a/scriptsV2/ubuntu-16.04_k8-1.17_weave-2.6.0_rev2/cluster-upgrade/master-cni-apply.sh#L6)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Better to version here as well like above
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[templateV2.yaml, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension-templates/24#-MVIbQsH1boSVTCL3eI4:-MVSiPq122FzxH_JhKHn:bpswrv1) ([raw file](https://github.com/vmware/container-service-extension-templates/blob/00aaf4f4bd96a6df007f40c317591c4556cfa42e/templateV2.yaml#L1)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

min and max are indeed mandatory fields starting CSE 3.1
</blockquote></details>

Renamed to `template_v2.yaml` and `scripts_v2/`

**Comment by Anirudh9794** [comment]
Reopening against upgrades branch

**Pull request closed without merging**
